steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--platform=linux/amd64'
      - '-t'
      - 'gcr.io/$PROJECT_ID/api-server:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/api-server:latest'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/api-server:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/api-server:latest'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'api-server'
      - '--image=gcr.io/$PROJECT_ID/api-server:$COMMIT_SHA'
      - '--region=$_REGION'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--max-instances=10'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--port=8080'
      - '--set-env-vars=RECAPTCHA_SECRET_KEY=6LcliBUsAAAAAAKUun3O7vvdrPUcc_PZfSJqdK2j'

images:
  - 'gcr.io/$PROJECT_ID/api-server:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/api-server:latest'

substitutions:
  _REGION: 'asia-northeast1'

options:
  machineType: 'N1_HIGHCPU_8'
